#app
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE     := CppEntry

MY_LDLIBS := -llog
MY_CFLAGS := -Werror
MY_C_INCLUDES := $(LOCAL_PATH)/..

MY_STATIC_LIBRARIES := libxml2

LOCAL_SRC_FILES  := CppEntry.cpp \
                    XMLUtils.cpp \
                    XMLNode.cpp
                    
LOCAL_LDLIBS := $(MY_LDLIBS) 


LOCAL_C_INCLUDES := $(MY_C_INCLUDES)

LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_LDLIBS := $(MY_LDLIBS) 

LOCAL_STATIC_LIBRARIES := $(MY_STATIC_LIBRARIES)
LOCAL_EXPORT_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_EXPORT_CFLAGS     := $(MY_CFLAGS)
LOCAL_EXPORT_LDLIBS     := $(MY_LDLIBS)

include $(BUILD_SHARED_LIBRARY)
#include $(BUILD_STATIC_LIBRARY)
